name: Deploy app

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_TAG }}:latest

  # deploy:
  #   name: Deploy app
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Pull image
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_IP }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #         script: |
  #           cd ${{ secrets.SSH_PATH }}
  #           docker pull ${{ secrets.DOCKER_HUB_TAG }}:latest

  #     - name: Run app
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_IP }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #         script: |
  #           cd ${{ secrets.SSH_PATH }}
  #           cd ..
  #           ./scripts/init.sh
  #           docker system prune -f
